swagger: "2.0"
info:
  title: My Chi API
  description: "API for my Chi application"
  version: "1.0.0"
consumes:
  - application/json
produces:
  - application/json
paths:
  /route:
    post:
      summary: Get route start and end
      description: Returns the start and end points of a route.
      consumes:
        - application/json
      parameters:
        - name: body
          in: body
          description: Request payload
          required: true
          schema:
            type: object
            required:
              - route
            properties:
              route:
                type: array
                items:
                  type: array
                  items:
                    type: string
      responses:
        "200":
          description: Success response
          schema:
            $ref: "#/definitions/RoutePoints"
        "400":
          description: Bad request
          schema:
            $ref: "#/definitions/ErrorResponse"
definitions:
  RoutePoints:
    type: object
    properties:
      source:
        type: string
      destination:
        type: string
  ErrorResponse:
    type: object
    properties:
      error:
        type: string
